URL_SERVICE =  "https://cnt-2ba0b97f-8f09-47e2-82b0-7bb7a5e96974.containerhub.tripleten-services.com/docs"
DOC_PATH = "/docs/"
MAIN_PATH = "/main/"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCT_KITS_PATH = "/api/v1/products/kits/"
